### ISSUE TITLE
Books that couldn't be processed

### ISSUE THREAD

**Issue by soapdog** [Himalayan-Academy/epub2pwa#1]
I am making this issue to track the progress on fixing broken books for uploading as PWAs. 

After the initial export, there are 71 file_ids which doesn't have a corresponding PWA on disk. Some of these are test entries on the database (which we should delete at some point) and others are duplicate entries. The full list of the books I am checking is:

atti-chudi
bhojana-mantra
bodhinatha-ashtottara
coloring-books
comment-elever-les-enfants-avec-amour_fr
dancing-with-siva_mr
dancing-with-siva_ta
ganesha-puja_bw
ganesha-puja_color
guru-gita
guru-mantra
gurudeva-ashtottara
gurudeva-weekly-calendar
hatha-yoga_ei
healing-sacred-vows-and-trance-possession-ei
hindu-history-chapter-five-lesson-plans
hindu-history-chapter-four-lesson-plans
hindu-history-chapter-one-lesson-plans
hindu-history-chapter-three-lesson-plans
hindu-history-chapter-two-lesson-plans
hindu-lexicon-online
hinduism-today-current-issue
hinduisms-nine-beliefs_hi
jazn-the-self-god_pl
kadavul-hindu-temple
kamika-agama-purva-pada-part-1
kamika-agama-uttara-pada-part-2
kamika-agama_grantha
karana-agama-grantha
karma-reincarnation-vivekananda_ei
kirana-agama-english-translation
kularnava-tantra
mantra-pushpam
matanga-agama-vidya-pada_v2
mauritius-spiritual-park
mrgendra-agama-vidya-pada
natchintanai-song-book
pauskara-agama-vidya-pada_v2
raurava-agama-vidya-pada
reflections
sacred-pledge
sacred-vows
saiva-booshanam_sa-ta
saiva-kala-viveka_grantha
saivite-creed-in-gujarati
sarvagnanotaraagam
sarvajnanottara-agama-yoga-pada
shanti-mantra
siddantha-prakashika_sa-en
siddhanta-course-1977
siva-mahothsava-sangraha
siva-puja-sthavam-tganeshan
siva-puja-sthavam_gss-tm
sivagnana-bodha_sa-en
sivagnana-siddiyar-parapakkam
sivaneri-prakasham
sivas-cosmic-dance
solemn-aspirations
sri-sivapanchavarana-sthothram
sthuthi-sangraha_sa
temple-worship
testament-of-truth
ukrainian-9-beliefs_uk
varuna-paddhathi
vedanta-course

I've already removed from this list the books that were obviously bad entries such as test books.

**Comment by soapdog** [comment]
# atti-chudi

Doesn't have an epub in the folder. Maybe it was never uploaded.

**Comment by soapdog** [comment]
#  bhojana-mantra
Is not a book in epub format but a PDF.

**Comment by soapdog** [comment]
#  bodhinatha-ashtottara
Is not an epub but a PDF.

**Comment by soapdog** [comment]
#  coloring-books
This folder is empty. Maybe the book was never uploaded or processed through hapman. No cover, nothing. It is as if it was entered directly into the database with phpMyAdmin.

**Comment by soapdog** [comment]
#  comment-elever-les-enfants-avec-amour_fr
The covers are present but there is no epub file.

**Comment by soapdog** [comment]
#  dancing-with-siva_mr
No epub in folder

**Comment by soapdog** [comment]
#  dancing-with-siva_ta
There is a PDF on the folder but no EPUB

**Comment by soapdog** [comment]
#  ganesha-puja_bw
No epub in folder, just PDF

**Comment by soapdog** [comment]
#  ganesha-puja_color
No epub in folder, just PDF

**Comment by soapdog** [comment]
#  guru-gita
The folder is empty.

**Comment by soapdog** [comment]
#  guru-mantra
No epub in folder, just PDF

**Comment by soapdog** [comment]
#  gurudeva-ashtottara
No epub in folder, just PDF

**Comment by soapdog** [comment]
#  gurudeva-weekly-calendar
Folder is empty

**Comment by soapdog** [comment]
#  hatha-yoga_ei
Only a PDF present and with the wrong id ` hatha-yoga_ht.pdf`.

**Comment by soapdog** [comment]
#  healing-sacred-vows-and-trance-possession-ei
Folder is empty

**Comment by soapdog** [comment]
#  hindu-history-chapter-five-lesson-plans
Only PDF and DOCX files present, no epub.

**Comment by soapdog** [comment]
#  hindu-history-chapter-four-lesson-plans
Only PDF and DOCX files present, no epub.

**Comment by soapdog** [comment]
#  hindu-history-chapter-one-lesson-plans
Only PDF and DOCX files present, no epub.

**Comment by soapdog** [comment]
#  hindu-history-chapter-three-lesson-plans
Only PDF and DOCX files present, no epub.

**Comment by soapdog** [comment]
# hindu-history-chapter-two-lesson-plans
Only PDF and DOCX files present, no epub.

**Comment by soapdog** [comment]
#  hindu-lexicon-online
folder is empty. I suspect this is a bad entry from when we were building the first lexicon...

**Comment by soapdog** [comment]
#  hinduism-today-current-issue
No epub file present, only covers.

**Comment by soapdog** [comment]
#  hinduisms-nine-beliefs_hi
No epub in folder, only PDF

**Comment by soapdog** [comment]
#  jazn-the-self-god_pl
Folder is empty

**Comment by soapdog** [comment]
#  kadavul-hindu-temple
Folder is empty

**Comment by soapdog** [comment]
#  kamika-agama-purva-pada-part-1
No epub found, just a PDF

**Comment by soapdog** [comment]
#  kamika-agama-purva-pada-part-2
No epub found, just a PDF

**Comment by soapdog** [comment]
#  kamika-agama_grantha
No epub in folder but multiple PDFs

**Comment by soapdog** [comment]
#  karana-agama-grantha
No epub in folder but a PDF

**Comment by soapdog** [comment]
#  karma-reincarnation-vivekananda_ei
The conversion is breaking during cover processing as seen in:

```
devhap@shiv:~/public_html/andre/epub2pwa$ ./target/release/epub2pwa -b karma-reincarnation-vivekananda_ei.json
Book: Karma and Reincarnation - Himalayan Academy (2015)
Copying static resources...
  copy: mobile.css
  copy: logo.svg
  copy: reader.css
  copy: app.js
  copy: sw.js
Total resources listed in Epub: 13
Extracting cover...
Compressing cover...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("first two bytes is not a SOI marker")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Press any key to continue...
``` 

I suspect this is happening because the cover is a PNG and I was assuming JPEG. Working on it.

---
Made changes to the cover routine and the book processed but somehow the spine is wrong and the book is not working correctly. It jumps from the cover to the last chapter.
---
The code was fixed to be able to handle book. The processed version is at https://dev.himalayanacademy.com/media/books/karma-reincarnation-vivekananda_ei/web

**Comment by soapdog** [comment]
#  kirana-agama-english-translation
It is a PDF and not an EPUB

**Comment by soapdog** [comment]
#  kularnava-tantra
Folder is empty

**Comment by soapdog** [comment]
# mantra-pushpan
It is a PDF and not an EPUB

**Comment by soapdog** [comment]
#  matanga-agama-vidya-pada_v2
There are multiple PDFs inside but no EPUB

**Comment by soapdog** [comment]
# mauritius-spiritual-park
Folder is empty

**Comment by soapdog** [comment]
#  mrgendra-agama-vidya-pada
It is a PDF not an EPUB

**Comment by soapdog** [comment]
# natchintanai-song-book
Folder is empty

**Comment by soapdog** [comment]
#  pauskara-agama-vidya-pada_v2
There are multiple PDFs inside but no epub

**Comment by soapdog** [comment]
#  raurava-agama-vidya-pada
It is a PDF and not an epub

**Comment by soapdog** [comment]
# reflections
Folder is empty

**Comment by soapdog** [comment]
#  sacred-pledge
Folder is empty

**Comment by soapdog** [comment]
# sacred-vows
Folder is empty

**Comment by soapdog** [comment]
#  saiva-booshanam_sa-ta
It is a PDF and not an epub

**Comment by soapdog** [comment]
#  saiva-kala-viveka_grantha
Multiple PDFs inside, some with wrong capitalization. Might be worth a look. There is no epub.

**Comment by soapdog** [comment]
#  saivite-creed-in-gujarati
Folder is empty

**Comment by soapdog** [comment]
# sarvagnanotaraagam
It is a PDF not an epub

**Comment by soapdog** [comment]
#  sarvajnanottara-agama-yoga-pada
It is a PDF and not an epub

**Comment by soapdog** [comment]
#  shanti-mantra
It is a PDF and not an epub

**Comment by soapdog** [comment]
#  siddantha-prakashika_sa-en
It is a PDF and not an epub

**Comment by soapdog** [comment]
#  siddhanta-course-1977
Folder is empty

**Comment by soapdog** [comment]
# siva-mahothsava-sangraha
Multiple PDFs inside but no epub

**Comment by soapdog** [comment]
#  siva-puja-sthavam-tganeshan
It is a PDF and not an epub

**Comment by soapdog** [comment]
# siva-puja-sthavam_gss-tm
It is a PDF and not an epub

**Comment by soapdog** [comment]
# sivagnana-bodha_sa-en
There are multiple PDF inside but no epub

**Comment by soapdog** [comment]
# sivagnana-siddiyar-parapakkam
It is a PDF, not an epub

**Comment by soapdog** [comment]
# sivaneri-prakasham
It is a PDF not an epub

**Comment by soapdog** [comment]
# sivas-cosmic-dance
Folder is empty

**Comment by soapdog** [comment]
# solemn-aspirations
Folder is empty

**Comment by soapdog** [comment]
# sri-sivapanchavarana-sthothram
It is a PDF and not an epub

**Comment by soapdog** [comment]
# sthuthi-sangraha_sa
It is a PDF and not an epub

**Comment by soapdog** [comment]
# temple-worship
It is a PDF not an epub

**Comment by soapdog** [comment]
# testament-of-truth
Wrong capitalization on epub file. The book file is probably coming from the `item_formats` table instead of the convention we used later which is naming it like the file_id.

After changing the job to use the correct filename, the conversion breaks processing some resource as can be seen in:
```
Total resources listed in Epub: 33
Extracting cover...
Cover mime: image/jpeg
Compressing cover...
spine len: 27
spine cover
spine TofTruth
spine index1
spine contents
spine intro
spine preface
spine foreward
spine ch01
spine ch02
spine ch03
spine ch04
spine ch05
spine ch06
spine ch07
spine ch08
spine ch09
spine ch10
spine ch11
spine ch12
spine ch13
spine ch14
spine ch15
spine ch16
spine ch17
spine ch18
spine ch19
spine epi
Extracting resources...
Code:
# -> images
. -> HTML
C -> CSS
@ -> raw file resource

................@@.......thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FormatError("encountered COM with invalid length 2")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

---
There was something odd with the images from this book. They render fine in the web but my image handling library complains that they are corrupt. I've changed the code from the exporter to find out these edge cases and ignore them (as in they just copy the image without resizing). 

The book is now available at https://dev.himalayanacademy.com/media/books/testament-of-truth/web/

**Comment by soapdog** [comment]
# ukrainian-9-beliefs_uk
There are two PDFs inside (one with spaces in the name) but no EPUB

**Comment by soapdog** [comment]
# varuna-paddhathi
Is a PDF and not an epub

**Comment by soapdog** [comment]
# vedanta-course
Folder is empty

**Comment by soapdog** [comment]
@Brahmanathaswami check out, this is the result of processing our missing books. From all the list of unprocessed books, most were PDFs or empty folders. Just two were actually strange epubs which are now available.
